const WORKER='https://cotuong.starlinksatellitewifi.workers.dev';
const engine=new Engine();let game=null,moves=[],index=0,snapshots=[];const pieceNames={1:'Tốt',2:'Sĩ',3:'Tượng',4:'Mã',5:'Pháo',6:'Xe',7:'Tướng',8:'Tốt',9:'Sĩ',10:'Tượng',11:'Mã',12:'Pháo',13:'Xe',14:'Tướng'};
const $=id=>document.getElementById(id);function square(move,source){return source?engine.getSourceSquare(move):engine.getTargetSquare(move)}
function draw(){let h='<div class="grid">';for(let vr=0;vr<10;vr++)for(let vf=0;vf<9;vf++){const sq=(vr+2)*11+(vf+1),p=engine.getPiece(sq);h+=`<div class="sq" id="s${sq}">${p?`<img src="game/images/traditional_pieces/${p}.svg" alt="">`:''}</div>`}h+='</div>';$('board').innerHTML=h;drawOverlay()}
function drawOverlay(){const svg=$('overlay');svg.innerHTML='';if(index===0)return;const m=snapshots[index].move,from=square(m,true),to=square(m,false);const pos=s=>{const r=Math.floor(s/11)-2,f=s%11-1;return{x:(f+.5)*100/9,y:(r+.5)*100/10}};const a=pos(from),b=pos(to),ns='http://www.w3.org/2000/svg';svg.setAttribute('viewBox','0 0 100 100');const defs=document.createElementNS(ns,'defs');defs.innerHTML='<marker id="ah" markerWidth="4" markerHeight="4" refX="3.2" refY="2" orient="auto"><path d="M0,0 L4,2 L0,4 Z" fill="#c84335"/></marker>';svg.appendChild(defs);for(const [p,c] of [[a,'last-from'],[b,'last-to']]){const el=document.createElementNS(ns,'circle');el.setAttribute('cx',p.x);el.setAttribute('cy',p.y);el.setAttribute('r','3.7');el.setAttribute('class',c);svg.appendChild(el)}const line=document.createElementNS(ns,'line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class','move-line');line.setAttribute('marker-end','url(#ah)');svg.appendChild(line)}
function snapshot(){return{position:JSON.stringify(engine.getBoard()),side:engine.getSide(),sixty:engine.getSixty(),hashKey:engine.getHashKey(),kingSquare:JSON.stringify(engine.getKingSquare())}}
function restore(i){const s=snapshots[i];engine.setPosition(JSON.parse(s.position));engine.setSide(s.side);engine.setSixty(s.sixty);engine.setHashKey(s.hashKey);engine.setKingSquare(JSON.parse(s.kingSquare));index=i;draw();updateMeta();if(i>0)analyzeMove()}
function loadGame(id){game=FamousGames.find(x=>x.id===Number(id))||FamousGames[0];moves=game.moves.trim().split(/\s+/);engine.setBoard(engine.START_FEN);snapshots=[{...snapshot(),move:0,piece:0,moveText:''}];for(const ms of moves){const enc=engine.moveFromString(ms),src=engine.getSourceSquare(enc),piece=engine.getPiece(src);engine.loadMoves(ms);snapshots.push({...snapshot(),move:enc,piece,moveText:ms})}index=0;restore(0);$('redPlayer').textContent=game.red;$('blackPlayer').textContent=game.black;$('eventName').textContent=game.event;$('headline').textContent='Sẵn sàng khám phá một danh cục';$('summary').textContent='Bấm “Nước tiếp theo” để xem từng nước và nghe AI giải thích ý đồ của hai bên.';$('friendlyMove').textContent='Chưa có nước đi';$('intent').textContent='Đang chờ nước đầu tiên.';$('risk').textContent='Quan sát cách bố trí quân trước khi kết luận.';$('lessons').innerHTML='<li>Hãy đoán nước tiếp theo trước khi bấm Next.</li>';}
function updateMeta(){$('moveCount').textContent=index===0?'Bắt đầu ván cờ':`Đã xem ${index}/${moves.length} nước`;$('sideTurn').textContent=index===moves.length?'Kết thúc ván':(index%2===0?'Đến lượt Đỏ':'Đến lượt Đen');$('progressBar').style.width=(index/moves.length*100)+'%';$('prev').disabled=index===0;$('next').disabled=index===moves.length}
function friendly(){if(index===0)return'';const s=snapshots[index],m=s.move,from=square(m,true),to=square(m,false),side=index%2===1?'Đỏ':'Đen',name=pieceNames[s.piece]||'Quân';const fr=Math.floor(from/11)-2,ff=from%11-1,tr=Math.floor(to/11)-2,tf=to%11-1;let act;if(fr===tr)act='đi ngang';else if(name==='Mã')act='nhảy lên vị trí mới';else if(name==='Tượng')act='đi chéo để củng cố thế trận';else {const forward=side==='Đỏ'?tr<fr:tr>fr;act=forward?'tiến lên':'lùi về'}return `${side} đưa ${name} ${act}`}
async function analyzeMove(){const phrase=friendly();$('friendlyMove').textContent=phrase;$('aiStatus').textContent='AI đang bình luận…';$('commentary').classList.add('loading');const prev=moves.slice(Math.max(0,index-7),index).join(' ');try{const r=await fetch(WORKER+'/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'historical_replay',game:{event:game.event,red:game.red,black:game.black},moveNumber:Math.ceil(index/2),ply:index,side:index%2===1?'Đỏ':'Đen',friendlyMove:phrase,currentMove:snapshots[index].moveText,recentMoves:prev,phase:index<20?'khai cuộc':index<55?'trung cuộc':'tàn cuộc'})});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json(),x=d.analysis||d;$('headline').textContent=x.headline||phrase;$('summary').textContent=x.summary||'Nước đi này làm thay đổi cách hai bên kiểm soát thế trận.';$('intent').textContent=x.intent||'Bên đi đang cải thiện vị trí và chuẩn bị kế hoạch tiếp theo.';$('risk').textContent=x.risk||'Đối thủ cần kiểm tra các đòn chiếu, bắt quân và phản công trực tiếp.';$('lessons').innerHTML=(x.lessons||['Đừng chỉ nhìn quân vừa đi; hãy nhìn đường hoạt động vừa được mở ra.']).slice(0,3).map(v=>`<li>${v}</li>`).join('');$('curiosity').textContent=x.curiosity||'Hãy thử đoán nước đáp trả trước khi bấm Next.'}catch(e){$('headline').textContent=phrase;$('summary').textContent='Nước này giúp bên đi triển khai quân hoặc tranh quyền chủ động. Hãy nhìn cả những đường vừa mở ra phía sau quân cờ.';$('intent').textContent='Cải thiện vị trí quân và buộc đối thủ phải phản ứng.';$('risk').textContent='Cần đề phòng nước chiếu, bắt quân hoặc phản công vào trung lộ.';$('lessons').innerHTML='<li>Một nước hay thường vừa làm việc của mình, vừa hạn chế kế hoạch của đối thủ.</li><li>Quan sát quân nào được giải phóng sau nước đi này.</li>';$('curiosity').textContent='Đối thủ sẽ đổi quân, phòng thủ hay phản công ngay?'}finally{$('aiStatus').textContent='Đã bình luận';$('commentary').classList.remove('loading')}}
function init(){const sel=$('gameSelect');FamousGames.forEach(g=>{const o=document.createElement('option');o.value=g.id;o.textContent=`${g.red} – ${g.black} · ${g.event}`;sel.appendChild(o)});sel.onchange=()=>loadGame(sel.value);$('next').onclick=()=>{if(index<moves.length)restore(index+1)};$('prev').onclick=()=>{if(index>0)restore(index-1)};$('restart').onclick=()=>restore(0);loadGame(FamousGames[0].id)}init();
