(() => {
'use strict';
const WORKER_BASE='https://cotuong.starlinksatellitewifi.workers.dev';
const engine=new Engine();
engine.setBoard(engine.START_FEN);
const PIECE_MAP={1:'red-pawn',2:'red-advisor',3:'red-elephant',4:'red-knight',5:'red-cannon',6:'red-rook',7:'red-king',8:'black-pawn',9:'black-advisor',10:'black-elephant',11:'black-knight',12:'black-cannon',13:'black-rook',14:'black-king'};
const PIECE_NAME={1:'Tốt đỏ',2:'Sĩ đỏ',3:'Tượng đỏ',4:'Mã đỏ',5:'Pháo đỏ',6:'Xe đỏ',7:'Tướng đỏ',8:'Tốt đen',9:'Sĩ đen',10:'Tượng đen',11:'Mã đen',12:'Pháo đen',13:'Xe đen',14:'Tướng đen'};
const els={pieces:$('#piecesLayer'),selection:$('#selectionLayer'),turn:$('#turnLabel'),state:$('#engineState'),title:$('#suggestionTitle'),text:$('#suggestionText'),feed:$('#decisionFeed'),count:$('#moveCount'),toast:$('#toast'),setup:$('#setupDialog'),history:$('#historyDialog'),review:$('#reviewDialog')};
let selected=null,flip=false,searching=false,lastSuggestion=null,sessionId=crypto.randomUUID(),startedAt=new Date().toISOString(),decisionLog=[];
let setupMode=false,setupPiece=1,setupBoard=new Map();
const coordMap=new Map(); for(let sq=0;sq<154;sq++){const c=engine.squareToString(sq);if(c&&c!=='xx')coordMap.set(c,sq)}
function $(s){return document.querySelector(s)}
function squareToPoint(sq){const c=engine.squareToString(Number(sq));if(!c||c==='xx')return null;let f=c.charCodeAt(0)-97,r=Number(c[1]);if(flip){f=8-f;r=9-r}return{x:10+f*10,y:92.78-r*9.44,file:f,rank:r}}
function pieceColor(p){return p>=8?'black':p>0?'red':null}
function currentColor(){return engine.getSide()===engine.COLOR.RED?'red':'black'}
function renderBoard(){const frag=document.createDocumentFragment();for(let rank=0;rank<10;rank++){for(let file=0;file<9;file++){const coord=String.fromCharCode(97+file)+rank;const sq=coordMap.get(coord),p=engine.getPiece(sq);if(!p)continue;const pt=squareToPoint(sq),b=document.createElement('button');b.className='piece'+(selected===sq?' selected':'');b.style.left=pt.x+'%';b.style.top=pt.y+'%';b.dataset.square=sq;b.setAttribute('aria-label',PIECE_NAME[p]);const img=document.createElement('img');img.src=`/assets/pieces/${PIECE_MAP[p]}.svg?v=2`;img.alt=PIECE_NAME[p];img.width=100;img.height=100;img.decoding='async';img.draggable=false;img.addEventListener('error',()=>{img.hidden=true;b.classList.add('piece-fallback');b.dataset.label=PIECE_NAME[p].split(' ')[0]}, {once:true});b.appendChild(img);b.addEventListener('click',()=>tapSquare(sq));frag.appendChild(b)}}els.pieces.replaceChildren(frag);renderTargets();els.turn.textContent=currentColor()==='red'?'Đỏ đang đi':'Đen đang đi';}
function legalMovesFrom(sq){return engine.generateLegalMoves().filter(x=>engine.getSourceSquare(x.move)===Number(sq))}
function renderTargets(){els.selection.replaceChildren();if(selected==null)return;const frag=document.createDocumentFragment();for(const item of legalMovesFrom(selected)){const target=engine.getTargetSquare(item.move),pt=squareToPoint(target),dot=document.createElement('button');dot.className='target-dot';dot.style.left=pt.x+'%';dot.style.top=pt.y+'%';dot.ariaLabel='Đi đến đây';dot.addEventListener('click',()=>tapSquare(target));frag.appendChild(dot)}els.selection.appendChild(frag)}
function tapSquare(sq){if(setupMode){if(setupBoard.has(Number(sq)))setupBoard.delete(Number(sq));else setupBoard.set(Number(sq),setupPiece);renderSetupBoard();return}if(searching)return;const p=engine.getPiece(Number(sq));if(selected==null){if(!p||pieceColor(p)!==currentColor()){toast('Hãy chọn quân của bên đang đi');return}selected=Number(sq);renderBoard();return}if(p&&pieceColor(p)===currentColor()){selected=Number(sq);renderBoard();return}const moveStr=engine.squareToString(selected)+engine.squareToString(Number(sq)),move=engine.moveFromString(moveStr);if(!move){toast('Nước này không hợp lệ');selected=null;renderBoard();return}const beforePiece=engine.getPiece(selected),capture=engine.getPiece(Number(sq));engine.loadMoves(moveStr);decisionLog.push({ply:engine.getMoves().length,side:pieceColor(beforePiece),move:moveStr,piece:PIECE_NAME[beforePiece],capture:capture?PIECE_NAME[capture]:null,played_at:new Date().toISOString()});selected=null;lastSuggestion=null;renderBoard();renderFeed();scheduleHint()}
function formatMove(move){const from=engine.getSourceSquare(move),to=engine.getTargetSquare(move),p=engine.getPiece(from),a=engine.squareToString(from),b=engine.squareToString(to);const df=b.charCodeAt(0)-a.charCodeAt(0),dr=Number(b[1])-Number(a[1]);let action='đi';if(df===0)action=dr>0?'tiến lên':'lùi xuống';else if(dr===0)action='đi ngang';else action='đi chéo';const side=pieceColor(p)==='red'?'Đỏ':'Đen';return{title:`${PIECE_NAME[p]} ${action}`,text:`${side} nên ưu tiên nước này để giữ thế chủ động và hạn chế phương án phản công của đối thủ.`,piece:PIECE_NAME[p],move:engine.squareToString(from)+engine.squareToString(to)}}
function heuristicReason(move){const from=engine.getSourceSquare(move),to=engine.getTargetSquare(move),p=engine.getPiece(from),capture=engine.getPiece(to);let reasons=[];if(capture)reasons.push(`đổi hoặc bắt ${PIECE_NAME[capture]} để tạo lợi thế`);if([5,6,12,13].includes(p))reasons.push('phát huy quân chủ lực trên đường thông thoáng');if([4,11].includes(p))reasons.push('đưa Mã tới điểm linh hoạt hơn');if([1,8].includes(p))reasons.push('mở thêm không gian và giữ điểm quan trọng');if(!reasons.length)reasons.push('củng cố đội hình trước khi mở đợt tấn công mới');return `Liễu Đại Hoa thường chọn cách thực dụng: ${reasons.join(', ')}.`}
function scheduleHint(){
  const run=()=>requestHint();
  if('requestIdleCallback' in window) requestIdleCallback(run,{timeout:350});
  else setTimeout(run,120);
}
function requestHint(){if(searching)return;searching=true;els.state.textContent='Đang tính…';els.title.textContent='Liễu Đại Hoa đang cân nhắc';els.text.textContent='Hệ thống kiểm tra các nước hợp lệ và ưu tiên phương án chắc chắn, dễ duy trì áp lực.';setTimeout(()=>{try{engine.resetTimeControl();const timing=engine.getTimeControl(),now=Date.now();timing.timeSet=1;timing.time=260;timing.stopTime=now+260;engine.setTimeControl(timing);const move=engine.search(32);if(!move)throw new Error('Không có nước hợp lệ');lastSuggestion=move;const f=formatMove(move);els.title.textContent=f.title;els.text.textContent=heuristicReason(move);highlightSuggested(move)}catch(e){els.title.textContent='Chưa tìm được phương án';els.text.textContent='Thế cờ có thể đã kết thúc hoặc cần kiểm tra lại cách xếp quân.'}finally{searching=false;els.state.textContent='Sẵn sàng'}} ,30)}
function highlightSuggested(move){selected=engine.getSourceSquare(move);renderBoard();}
function renderFeed(){els.count.textContent=`${decisionLog.length} nước`;if(!decisionLog.length){els.feed.innerHTML='<div class="empty-state">Các quyết định sẽ xuất hiện tại đây sau khi bạn bắt đầu di chuyển quân.</div>';return}els.feed.innerHTML=decisionLog.slice().reverse().map(x=>`<article class="decision-item"><span class="move-no">NƯỚC ${x.ply} · ${x.side==='red'?'ĐỎ':'ĐEN'}</span><strong>${escapeHtml(x.piece)} đã di chuyển</strong><p>${x.capture?`Nước này bắt ${escapeHtml(x.capture)} và làm thay đổi cán cân trên bàn cờ.`:'Nước đi được ghi lại để Gemini phân tích toàn bộ mạch quyết định sau khi bạn lưu ván.'}</p></article>`).join('')}
function undo(){try{engine.takeBack();decisionLog.pop();selected=null;lastSuggestion=null;renderBoard();renderFeed();requestHint()}catch{toast('Không còn nước để đi lại')}}
function newGame(){if(!confirm('Bắt đầu ván mới và bỏ lịch sử hiện tại?'))return;engine.setBoard(engine.START_FEN);decisionLog=[];sessionId=crypto.randomUUID();startedAt=new Date().toISOString();selected=null;renderBoard();renderFeed();requestHint()}
function openSetup(){setupMode=true;setupBoard.clear();for(let sq=0;sq<154;sq++){const p=engine.getPiece(sq);if(p)setupBoard.set(sq,p)}buildPalette();els.setup.showModal();}
function buildPalette(){const palette=$('#palette');palette.innerHTML='';for(const [p,asset] of Object.entries(PIECE_MAP)){const b=document.createElement('button');b.type='button';b.className='palette-piece'+(Number(p)===setupPiece?' active':'');b.innerHTML=`<img src="/assets/pieces/${asset}.svg" alt="${PIECE_NAME[p]}">`;b.onclick=()=>{setupPiece=Number(p);buildPalette()};palette.appendChild(b)}}
function fenFromSetup(){let rows=[];for(let rank=9;rank>=0;rank--){let row='',empty=0;for(let file=0;file<9;file++){const sq=coordMap.get(String.fromCharCode(97+file)+rank),p=setupBoard.get(sq)||0;if(!p){empty++;continue}if(empty){row+=empty;empty=0}row+=['','P','A','B','N','C','R','K','p','a','b','n','c','r','k'][p]}if(empty)row+=empty;rows.push(row)}return rows.join('/')+` ${$('#setupSide').value==='red'?'w':'b'} - - 0 1`}
function applySetup(){try{engine.setBoard(fenFromSetup());decisionLog=[];sessionId=crypto.randomUUID();startedAt=new Date().toISOString();setupMode=false;els.setup.close();renderBoard();renderFeed();requestHint()}catch{toast('Thế cờ chưa hợp lệ')}}
async function saveGame(){if(!decisionLog.length){toast('Hãy đi ít nhất một nước trước khi lưu');return}const btn=$('#saveBtn');btn.disabled=true;btn.textContent='Đang lưu…';try{const payload={session_id:sessionId,title:`Ván luyện tập ${new Date().toLocaleDateString('vi-VN')}`,started_at:startedAt,ended_at:new Date().toISOString(),moves:decisionLog,move_text:engine.getMoves(),result:detectResult(),device:'mobile-web'};const res=await fetch(`${WORKER_BASE}/api/sessions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error(await res.text());toast('Đã lưu ván và gửi Gemini phân tích');}catch(e){console.error(e);toast('Chưa thể lưu ván. Kiểm tra Worker và D1.')}finally{btn.disabled=false;btn.textContent='Lưu ván'}}
function detectResult(){try{return engine.generateLegalMoves().length===0?(currentColor()==='red'?'black_win':'red_win'):'unfinished'}catch{return'unfinished'}}
async function openHistory(){els.history.showModal();const list=$('#historyList');list.innerHTML='<div class="empty-state">Đang tải lịch sử…</div>';try{const r=await fetch(`${WORKER_BASE}/api/sessions?limit=30`),d=await r.json();if(!d.items?.length){list.innerHTML='<div class="empty-state">Bạn chưa lưu ván nào.</div>';return}list.innerHTML=d.items.map(x=>`<article class="history-item"><div><strong>${escapeHtml(x.title)}</strong><p>${x.move_count} nước · ${new Date(x.created_at).toLocaleString('vi-VN')} · ${statusLabel(x.analysis_status)}</p></div><button data-id="${x.id}">Xem lại</button></article>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>openReview(b.dataset.id))}catch{list.innerHTML='<div class="empty-state">Không tải được lịch sử. Hãy kiểm tra Worker.</div>'}}
async function openReview(id){els.history.close();els.review.showModal();$('#reviewContent').innerHTML='<div class="empty-state">Đang mở bản phân tích…</div>';try{const r=await fetch(`${WORKER_BASE}/api/sessions/${encodeURIComponent(id)}`),d=await r.json();$('#reviewTitle').textContent=d.title||'Ván cờ của bạn';const a=d.analysis||{};$('#reviewContent').innerHTML=`<section class="review-section"><h3>Tóm tắt ván cờ</h3><p>${escapeHtml(a.summary||'Gemini đang hoàn thiện bản phân tích. Hãy quay lại sau.')}</p></section><section class="review-section"><h3>Điểm làm tốt</h3>${listHtml(a.strengths)}</section><section class="review-section"><h3>Điểm nên cải thiện</h3>${listHtml(a.improvements)}</section><section class="review-section"><h3>Cách Liễu Đại Hoa có thể suy nghĩ</h3><p>${escapeHtml(a.liu_dahua_lens||'Chưa có dữ liệu.')}</p></section><section class="review-section"><h3>Ba bài học cần nhớ</h3>${listHtml(a.lessons)}</section>`}catch{$('#reviewContent').innerHTML='<div class="empty-state">Không tải được bản phân tích.</div>'}}
function statusLabel(s){return s==='complete'?'Đã phân tích':s==='processing'?'Đang phân tích':'Đang chờ'}
function listHtml(v){return Array.isArray(v)&&v.length?`<ul>${v.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'<p>Chưa có dữ liệu.</p>'}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}
$('#undoBtn').onclick=undo;$('#hintBtn').onclick=requestHint;$('#saveBtn').onclick=saveGame;$('#newBtn').onclick=newGame;$('#setupBtn').onclick=openSetup;$('#flipBtn').onclick=()=>{flip=!flip;renderBoard()};$('#historyBtn').onclick=openHistory;$('#closeHistory').onclick=()=>els.history.close();$('#closeReview').onclick=()=>els.review.close();$('#applySetup').onclick=e=>{e.preventDefault();applySetup()};$('#clearSetup').onclick=()=>{setupBoard.clear();toast('Đã xóa bàn. Chạm vào bàn để đặt quân.')};
// setup placement uses board background taps
$('#boardWrap').addEventListener('click',e=>{if(!setupMode||e.target.closest('.piece,.target-dot'))return;const rect=e.currentTarget.getBoundingClientRect(),xp=(e.clientX-rect.left)/rect.width,yp=(e.clientY-rect.top)/rect.height;let file=Math.round((xp-.10)/.10),visualRank=Math.round((yp-.0722)/.0944);file=Math.max(0,Math.min(8,file));visualRank=Math.max(0,Math.min(9,visualRank));let rank=9-visualRank;if(flip){file=8-file;rank=9-rank}const sq=coordMap.get(String.fromCharCode(97+file)+rank);if(setupBoard.has(sq))setupBoard.delete(sq);else setupBoard.set(sq,setupPiece);renderSetupBoard()});
function renderSetupBoard(){const original=[];for(let sq=0;sq<154;sq++){const p=engine.getPiece(sq);if(p)original.push([sq,p])}try{engine.setBoard(fenFromSetup());renderBoard()}catch{}finally{setupMode=true}}
renderBoard();renderFeed();els.state.textContent='Sẵn sàng';
})();
