const WORKER='https://cotuong.starlinksatellitewifi.workers.dev';
const $=id=>document.getElementById(id);
const glyphs={R:'俥',N:'傌',B:'相',A:'仕',K:'帥',C:'炮',P:'兵',r:'車',n:'馬',b:'象',a:'士',k:'將',c:'砲',p:'卒'};
const names={R:'Xe',N:'Mã',B:'Tượng',A:'Sĩ',K:'Tướng',C:'Pháo',P:'Tốt',r:'Xe',n:'Mã',b:'Tượng',a:'Sĩ',k:'Tướng',c:'Pháo',p:'Tốt'};
let games=[],sources=[],game=null,index=0,states=[];
function initialBoard(){const b={};'rnbakabnr'.split('').forEach((p,f)=>b[`${String.fromCharCode(97+f)}9`]=p);b.b7='c';b.h7='c';['a','c','e','g','i'].forEach(f=>b[`${f}6`]='p');'RNBAKABNR'.split('').forEach((p,f)=>b[`${String.fromCharCode(97+f)}0`]=p);b.b2='C';b.h2='C';['a','c','e','g','i'].forEach(f=>b[`${f}3`]='P');return b}
function applyMove(board,m){const n={...board},from=m.slice(0,2),to=m.slice(2,4);n[to]=n[from];delete n[from];return n}
function buildStates(){states=[{board:initialBoard(),move:null,captured:null}];let b=states[0].board;for(const m of game.moves){const captured=b[m.slice(2,4)]||null;b=applyMove(b,m);states.push({board:b,move:m,captured})}}
function pct(file,rank){return{x:(file/8)*100,y:((9-rank)/9)*100}}
function renderBoard(){const board=$('board');board.innerHTML='<div class="river"><span>楚 河</span><span>漢 界</span></div><div class="palace top"></div><div class="palace bottom"></div>';const state=states[index];for(const [sq,p] of Object.entries(state.board)){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),pos=pct(f,r),el=document.createElement('div');el.className=`piece ${p===p.toUpperCase()?'red':'black'}`;el.style.left=pos.x+'%';el.style.top=pos.y+'%';el.textContent=glyphs[p];el.title=(p===p.toUpperCase()?'Đỏ ':'Đen ')+names[p];board.appendChild(el)}drawOverlay()}
function drawOverlay(){const svg=$('overlay');svg.innerHTML='';if(!states[index]?.move)return;const m=states[index].move,a=pct(m.charCodeAt(0)-97,Number(m[1])),b=pct(m.charCodeAt(2)-97,Number(m[3]));svg.innerHTML=`<defs><marker id="arrow" markerWidth="14" markerHeight="14" refX="10" refY="5" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L10,5 L0,10 z" fill="#c43b31"/></marker></defs><circle class="move-ring from" cx="${a.x*9}" cy="${a.y*10}" r="34"/><line class="move-arrow" x1="${a.x*9}" y1="${a.y*10}" x2="${b.x*9}" y2="${b.y*10}" marker-end="url(#arrow)"/><circle class="move-ring to" cx="${b.x*9}" cy="${b.y*10}" r="34"/>`}
function friendlyMove(){if(index===0)return'';const m=states[index].move,p=states[index-1].board[m.slice(0,2)],side=p===p.toUpperCase()?'Đỏ':'Đen',fr=Number(m[1]),tr=Number(m[3]),ff=m.charCodeAt(0),tf=m.charCodeAt(2);let action;if(fr===tr)action='đi ngang';else if(names[p]==='Mã')action='nhảy lên điểm mới';else if(names[p]==='Tượng')action='đi chéo';else{const forward=side==='Đỏ'?tr>fr:tr<fr;action=forward?'tiến lên':'lùi về'}return `${side} đưa ${names[p]} ${action}`}
function phase(){const ratio=index/game.moves.length;if(ratio<.28)return'khai cuộc';if(ratio<.75)return'trung cuộc';return'tàn cuộc'}
function chapter(){if(index===0)return'LỜI MỞ ĐẦU';const r=index/game.moves.length;if(r<.18)return'CHƯƠNG 1 · DÒ ĐƯỜNG';if(r<.38)return'CHƯƠNG 2 · TRANH QUYỀN CHỦ ĐỘNG';if(r<.62)return'CHƯƠNG 3 · GIẰNG CO';if(r<.84)return'CHƯƠNG 4 · BƯỚC NGOẶT';return'CHƯƠNG CUỐI · ĐỊNH ĐOẠT'}
async function ai(mode='move'){const token=`${game.id}:${index}:${mode}`;$('aiState').textContent='AI đang nối mạch câu chuyện…';try{const body={mode:mode==='intro'?'story_intro':mode==='ending'?'story_ending':'story_move',game:{title:game.title,red:game.red,black:game.black,event:game.event,year:game.year,result:game.result,termination:game.termination,source:game.source},ply:index,totalPlies:game.moves.length,phase:phase(),friendlyMove:friendlyMove(),currentMove:states[index]?.move||'',recentMoves:game.moves.slice(Math.max(0,index-8),index),captured:states[index]?.captured?names[states[index].captured]:null};const r=await fetch(WORKER+'/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(token!==`${game.id}:${index}:${mode}`)return;applyStory(d.analysis||d,mode)}catch(e){fallback(mode)}finally{$('aiState').textContent='Bình luận được tạo theo diễn biến hiện tại'}}
function applyStory(x,mode){if(mode==='ending'){showEnding(x);return}$('chapterTag').textContent=x.chapter||chapter();$('headline').textContent=x.headline||(index?friendlyMove():'Một cuộc đấu trí bắt đầu');$('narration').textContent=x.narration||x.summary||'Hai bên đang từng bước hé lộ kế hoạch.';$('intent').textContent=x.intent||'Bên vừa đi muốn cải thiện vị trí và chuẩn bị kế hoạch kế tiếp.';$('dilemma').textContent=x.opponent_dilemma||x.dilemma||'Đối thủ phải cân nhắc giữa phòng thủ và phản công.';$('lessons').innerHTML=(x.lessons||[x.lesson||'Một nước hay thường tạo ra nhiều hơn một mục đích.']).filter(Boolean).slice(0,3).map(v=>`<li>${v}</li>`).join('');$('nextHook').textContent=x.next_hook||x.curiosity||'Hãy thử đoán nước đáp trả trước khi bấm tiếp.'}
function showEnding(x){$('ending').classList.remove('hidden');$('endingTitle').textContent=x.ending_title||x.official_result||'Ván cờ khép lại';$('endingText').textContent=x.conclusion||'Hệ thống đã đi hết dữ liệu ván đấu.';$('endingConfidence').textContent=x.confidence_note||((game.result&&game.result!=='*')?'Kết quả lấy từ metadata nguồn.':'Kết luận này là nhận định từ thế cờ cuối vì nguồn chưa ghi rõ kết quả.')}
function fallback(mode){if(mode==='intro'){applyStory({chapter:'LỜI MỞ ĐẦU',headline:`${game.red} đối đầu ${game.black}`,narration:`Ván đấu tại ${game.event}. Hãy theo dõi cách hai bên giành quyền chủ động từ những nước đầu tiên.`,intent:'Đỏ sẽ là bên mở màn và đặt câu hỏi đầu tiên.',opponent_dilemma:'Đen cần chọn cách nhập cuộc phù hợp để không bị cuốn theo.',lessons:['Quan sát quân nào được phát triển trước.','Đừng chỉ nhìn nước đi; hãy nhìn đường quân vừa được mở.'],next_hook:'Nước đầu tiên sẽ tiết lộ phong cách nhập cuộc nào?'});return}if(mode==='ending'){showEnding({ending_title:game.result==='1-0'?'Đỏ thắng':game.result==='0-1'?'Đen thắng':game.result==='1/2-1/2'?'Hai bên hòa':'Dữ liệu ván đấu dừng tại đây',conclusion:game.result==='*'?'Nguồn hiện chưa ghi kết quả chính thức. Xét diễn biến cuối, cần engine hoặc metadata đáng tin cậy hơn để kết luận thắng thua.':'Kết quả được lấy từ dữ liệu ván đấu.',confidence_note:game.result==='*'?'Không khẳng định người thắng khi nguồn chưa đủ căn cứ.':'Kết quả chính thức từ metadata.'});return}applyStory({chapter:chapter(),headline:friendlyMove(),narration:'Nước vừa đi làm thay đổi cách hai bên kiểm soát bàn cờ. Hãy để ý những đường quân mới được mở ra.',intent:'Bên đi đang cải thiện vị trí hoặc buộc đối thủ phải phản ứng.',opponent_dilemma:'Đối thủ cần kiểm tra đòn chiếu, bắt quân và phản công trực tiếp.',lessons:['Một nước cờ mạnh thường vừa phát triển quân, vừa hạn chế đối thủ.','Quan sát quân nào được giải phóng sau nước đi này.'],next_hook:'Đối thủ sẽ đổi quân, phòng thủ hay phản công?'})}
function update(){renderBoard();$('moveCount').textContent=index===0?'Bắt đầu':`Nước ${index}/${game.moves.length}`;$('sideTurn').textContent=index===game.moves.length?'Kết thúc':index%2===0?'Đỏ sắp đi':'Đen sắp đi';$('progressBar').style.width=(index/game.moves.length*100)+'%';$('prev').disabled=index===0;$('next').disabled=index===game.moves.length;$('ending').classList.add('hidden');if(index===0)ai('intro');else if(index===game.moves.length)ai('ending');else ai('move')}
function selectGame(g){game=g;index=0;buildStates();$('gameTitle').textContent=g.title;$('gameEvent').textContent=[g.event,g.year].filter(Boolean).join(' · ');$('redPlayer').textContent=g.red;$('blackPlayer').textContent=g.black;$('library').close();update()}
function renderLibrary(){const q=$('search').value.toLowerCase(),src=$('sourceFilter').value;const list=games.filter(g=>(src==='all'||g.source?.name===src)&&`${g.title} ${g.red} ${g.black} ${g.event}`.toLowerCase().includes(q));$('gameList').innerHTML=list.map(g=>`<button class="game-card" data-id="${g.id}"><span><strong>${g.red} – ${g.black}</strong><small>${g.event}${g.year?' · '+g.year:''}</small></span><span class="source-chip">${g.source?.name||'Nguồn dữ liệu'}</span></button>`).join('');document.querySelectorAll('.game-card').forEach(b=>b.onclick=()=>selectGame(games.find(g=>g.id===b.dataset.id)))}
async function init(){[games,sources]=await Promise.all([fetch('/data/games.json').then(r=>r.json()),fetch('/data/sources.json').then(r=>r.json())]);const unique=[...new Set(games.map(g=>g.source?.name).filter(Boolean))];unique.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;$('sourceFilter').appendChild(o)});$('libraryBtn').onclick=()=>{$('library').showModal();renderLibrary()};$('search').oninput=renderLibrary;$('sourceFilter').onchange=renderLibrary;$('next').onclick=()=>{if(index<game.moves.length){index++;update()}};$('prev').onclick=()=>{if(index>0){index--;update()}};$('restart').onclick=()=>{index=0;update()};selectGame(games[0])}init();
