const API = 'https://cotuong.starlinksatellitewifi.workers.dev';
const $ = id => document.getElementById(id);
const pieceAssets={R:'red-rook',N:'red-knight',B:'red-elephant',A:'red-advisor',K:'red-king',C:'red-cannon',P:'red-pawn',r:'black-rook',n:'black-knight',b:'black-elephant',a:'black-advisor',k:'black-king',c:'black-cannon',p:'black-pawn'};
const names={R:'Xe',N:'Mã',B:'Tượng',A:'Sĩ',K:'Tướng',C:'Pháo',P:'Tốt',r:'Xe',n:'Mã',b:'Tượng',a:'Sĩ',k:'Tướng',c:'Pháo',p:'Tốt'};
let games=[], sources=[], game=null, index=0, states=[];
let playing=false, playTimer=null, speed=1;

function initialBoard(){const b={};'rnbakabnr'.split('').forEach((p,f)=>b[`${String.fromCharCode(97+f)}9`]=p);b.b7='c';b.h7='c';['a','c','e','g','i'].forEach(f=>b[`${f}6`]='p');'RNBAKABNR'.split('').forEach((p,f)=>b[`${String.fromCharCode(97+f)}0`]=p);b.b2='C';b.h2='C';['a','c','e','g','i'].forEach(f=>b[`${f}3`]='P');return b}
function applyMove(board,m){const n={...board},from=m.slice(0,2),to=m.slice(2,4);if(n[from]){n[to]=n[from];delete n[from]}return n}
function buildStates(){states=[{board:initialBoard(),move:null,captured:null}];let b=states[0].board;for(const m of game.moves){const captured=b[m.slice(2,4)]||null;b=applyMove(b,m);states.push({board:b,move:m,captured})}}
function pct(file,rank){return{x:(file/8)*100,y:((9-rank)/9)*100}}
function renderBoard(){const board=$('board');board.innerHTML='<div class="river"><span>楚 河</span><span>漢 界</span></div><div class="palace top"></div><div class="palace bottom"></div>';const state=states[index];for(const [sq,p] of Object.entries(state.board)){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),pos=pct(f,r),el=document.createElement('div'),img=document.createElement('img');el.className=`piece ${p===p.toUpperCase()?'red':'black'}`;el.style.left=pos.x+'%';el.style.top=pos.y+'%';el.title=(p===p.toUpperCase()?'Đỏ ':'Đen ')+names[p];img.src=`/assets/pieces/${pieceAssets[p]}.svg`;img.alt=el.title;img.draggable=false;el.appendChild(img);board.appendChild(el)}drawOverlay()}
function drawOverlay(){const svg=$('overlay');svg.innerHTML='';if(!states[index]?.move)return;const m=states[index].move,a=pct(m.charCodeAt(0)-97,Number(m[1])),b=pct(m.charCodeAt(2)-97,Number(m[3]));svg.innerHTML=`<defs><marker id="arrow" markerWidth="11" markerHeight="11" refX="9" refY="5" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L10,5 L0,10 z" fill="#d5961b"/></marker></defs><circle class="move-ring from" cx="${a.x*9}" cy="${a.y*10}" r="30"/><line class="move-arrow" x1="${a.x*9}" y1="${a.y*10}" x2="${b.x*9}" y2="${b.y*10}" marker-end="url(#arrow)"/><circle class="move-ring to" cx="${b.x*9}" cy="${b.y*10}" r="30"/>`}
function friendlyMove(){if(index===0)return'';const m=states[index].move,p=states[index-1].board[m.slice(0,2)];if(!p)return'Một nước cờ mới vừa diễn ra';const side=p===p.toUpperCase()?'Đỏ':'Đen',fr=Number(m[1]),tr=Number(m[3]);let action;if(fr===tr)action='đi ngang';else if(names[p]==='Mã')action='nhảy sang điểm mới';else if(names[p]==='Tượng')action='đi chéo';else{const forward=side==='Đỏ'?tr>fr:tr<fr;action=forward?'tiến lên':'lùi về'}return `${side} đưa ${names[p]} ${action}`}
function chapter(){if(index===0)return'LỜI MỞ ĐẦU';const r=index/game.moves.length;if(r<.18)return'CHƯƠNG 1 · DÒ ĐƯỜNG';if(r<.38)return'CHƯƠNG 2 · TRANH QUYỀN CHỦ ĐỘNG';if(r<.62)return'CHƯƠNG 3 · GIẰNG CO';if(r<.84)return'CHƯƠNG 4 · BƯỚC NGOẶT';return'CHƯƠNG CUỐI · ĐỊNH ĐOẠT'}
function fallbackStory(mode){if(mode==='intro')return{chapter:'LỜI MỞ ĐẦU',headline:`${game.red} đối đầu ${game.black}`,narration:`Ván đấu tại ${game.event||'một kỳ đài nổi tiếng'}. Hãy theo dõi cách hai bên giành quyền chủ động từ những nước đầu tiên.`,intent:'Đỏ sẽ đặt câu hỏi đầu tiên trên bàn cờ.',opponent_dilemma:'Đen cần chọn cách nhập cuộc phù hợp để không bị cuốn theo.',lessons:['Quan sát quân nào được phát triển trước.','Đừng chỉ nhìn nước đi; hãy nhìn đường quân vừa được mở.'],next_hook:'Nước đầu tiên sẽ hé lộ phong cách nhập cuộc nào?'};
if(mode==='ending')return{ending_title:game.result==='1-0'?'Đỏ thắng':game.result==='0-1'?'Đen thắng':game.result==='1/2-1/2'?'Hai bên hòa':'Dữ liệu ván đấu dừng tại đây',conclusion:game.result==='*'?'Nguồn chưa ghi kết quả chính thức nên hệ thống không tự khẳng định người thắng.':'Kết quả được lấy từ metadata của ván đấu.',confidence_note:game.result==='*'?'Chưa đủ căn cứ kết luận thắng thua.':'Kết quả chính thức từ nguồn dữ liệu.'};
return{chapter:chapter(),headline:friendlyMove(),narration:'Nước vừa đi làm thay đổi cách hai bên kiểm soát bàn cờ. Hãy để ý những đường quân mới được mở ra.',intent:'Bên đi đang cải thiện vị trí hoặc buộc đối thủ phải phản ứng.',opponent_dilemma:'Đối thủ phải cân nhắc giữa phòng thủ, đổi quân và phản công.',lessons:['Một nước mạnh thường tạo ra nhiều hơn một mục đích.','Quan sát quân nào được giải phóng sau nước đi này.'],next_hook:'Đối thủ sẽ phòng thủ hay chủ động phản công?'}
}
function storyForCurrent(){if(index===0)return game.intro||fallbackStory('intro');if(index===game.moves.length)return game.ending||fallbackStory('ending');return game.stories?.[String(index)]||fallbackStory('move')}
function applyStory(x,mode){const panel=document.querySelector('.story-panel');panel.classList.remove('story-transition');void panel.offsetWidth;panel.classList.add('story-transition');if(mode==='ending'){showEnding(x);return}$('chapterTag').textContent=x.chapter||chapter();$('headline').textContent=x.headline||(index?friendlyMove():'Một cuộc đấu trí bắt đầu');$('narration').textContent=x.narration||x.summary||'Hai bên đang từng bước hé lộ kế hoạch.';$('intent').textContent=x.intent||'Bên vừa đi muốn cải thiện vị trí và chuẩn bị kế hoạch tiếp theo.';$('dilemma').textContent=x.opponent_dilemma||x.dilemma||'Đối thủ phải cân nhắc giữa phòng thủ và phản công.';$('lessons').innerHTML=(x.lessons||[x.lesson||'Một nước hay thường tạo ra nhiều hơn một mục đích.']).filter(Boolean).slice(0,3).map(v=>`<li>${escapeHtml(v)}</li>`).join('');$('nextHook').textContent=x.next_hook||x.curiosity||'Hãy thử đoán nước đáp trả trước khi bấm tiếp.'}
function showEnding(x){$('ending').classList.remove('hidden');$('endingTitle').textContent=x.ending_title||x.official_result||'Ván cờ khép lại';$('endingText').textContent=x.conclusion||'Hệ thống đã đi hết dữ liệu ván đấu.';$('endingConfidence').textContent=x.confidence_note||((game.result&&game.result!=='*')?'Kết quả lấy từ metadata nguồn.':'Nguồn chưa ghi rõ kết quả.');$('chapterTag').textContent='KẾT CỤC';$('headline').textContent=x.ending_title||'Ván cờ khép lại';$('narration').textContent=x.conclusion||''}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function narrationDelay(){const s=storyForCurrent();const text=[s.headline,s.narration,s.intent,s.opponent_dilemma,s.next_hook].filter(Boolean).join(' ');return Math.max(4200,Math.min(11500,2600+text.length*24))*speed}
function stopAuto(){playing=false;clearTimeout(playTimer);playTimer=null;$('playIcon').textContent='▶';$('playLabel').textContent='Tự động';$('autoPlay').classList.remove('playing')}
function scheduleNext(){clearTimeout(playTimer);if(!playing)return;if(index>=game.moves.length){stopAuto();return}playTimer=setTimeout(()=>{index++;update();scheduleNext()},narrationDelay())}
function toggleAuto(){if(!game.cacheComplete)return;if(playing){stopAuto();return}if(index>=game.moves.length)index=0;playing=true;$('playIcon').textContent='Ⅱ';$('playLabel').textContent='Tạm dừng';$('autoPlay').classList.add('playing');update();scheduleNext()}
function updateCacheUi(){const btn=$('autoPlay'),badge=$('cacheBadge');if(game.cacheComplete){btn.disabled=false;btn.classList.add('ready');badge.textContent='Cuốn truyện đã sẵn sàng';badge.className='source-badge cached';$('aiState').textContent='Đang đọc bản bình luận đã lưu — không gọi AI trực tiếp'}else{btn.disabled=true;btn.classList.remove('ready');badge.textContent='Đang biên tập bản truyện';badge.className='source-badge pending';$('aiState').textContent='Có thể xem thủ công; tự động phát sẽ mở khi cache hoàn tất'}}
function update(){renderBoard();const ended=index===game.moves.length,redToMove=index%2===0;$('moveCount').textContent=index===0?'Bắt đầu':`Nước ${index}/${game.moves.length}`;$('sideTurn').textContent=ended?'Kết thúc':redToMove?'Đỏ sắp đi':'Đen sắp đi';$('progressBar').style.width=(index/game.moves.length*100)+'%';$('prev').disabled=index===0;$('next').disabled=ended;$('ending').classList.add('hidden');const redTurn=$('redTurn'),blackTurn=$('blackTurn');redTurn.textContent=ended?'Kết thúc':redToMove?'Đang đi':'Chờ lượt';blackTurn.textContent=ended?'Kết thúc':redToMove?'Chờ lượt':'Đang đi';redTurn.classList.toggle('active',!ended&&redToMove);blackTurn.classList.toggle('active',!ended&&!redToMove);const mode=index===0?'intro':ended?'ending':'move';applyStory(storyForCurrent(),mode);updateCacheUi()}
async function hydrateGame(summary){stopAuto();let full=null;try{const r=await fetch(`${API}/api/games/${encodeURIComponent(summary.id)}`,{cache:'no-store'});if(r.ok)full=(await r.json()).game}catch{};game=full||summary;if(!game.moves)throw new Error('Ván cờ chưa có dữ liệu nước đi');game.stories=game.stories||{};index=0;buildStates();$('gameTitle').textContent=game.title;$('gameEvent').textContent=[game.event,game.year].filter(Boolean).join(' · ');$('redPlayer').textContent=game.red;$('blackPlayer').textContent=game.black;$('library').close();update()}
function renderLibrary(){const q=$('search').value.toLowerCase(),src=$('sourceFilter').value;const list=games.filter(g=>(src==='all'||g.source?.name===src)&&`${g.title} ${g.red} ${g.black} ${g.event}`.toLowerCase().includes(q));$('gameList').innerHTML=list.map(g=>`<button class="game-card" data-id="${escapeHtml(g.id)}"><span><strong>${escapeHtml(g.red)} – ${escapeHtml(g.black)}</strong><small>${escapeHtml(g.event||'Danh cục')} ${g.year?' · '+escapeHtml(g.year):''}</small></span><span class="source-chip">${g.cacheComplete?'Đã có truyện':'Đang biên tập'}</span></button>`).join('');document.querySelectorAll('.game-card').forEach(b=>b.onclick=()=>hydrateGame(games.find(g=>g.id===b.dataset.id)))}
async function loadBundled(){const [g,s]=await Promise.all([fetch('/data/games.json').then(r=>r.json()),fetch('/data/sources.json').then(r=>r.json())]);return{games:g.map(x=>({...x,cacheComplete:false})),sources:s}}
async function init(){let payload;try{const r=await fetch(API+'/api/games?limit=100',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();if(!d.games?.length)throw 0;payload={games:d.games,sources:[]}}catch{payload=await loadBundled()}games=payload.games;sources=payload.sources;const unique=[...new Set(games.map(g=>g.source?.name).filter(Boolean))];unique.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;$('sourceFilter').appendChild(o)});$('libraryBtn').onclick=()=>{$('library').showModal();renderLibrary()};$('search').oninput=renderLibrary;$('sourceFilter').onchange=renderLibrary;$('next').onclick=()=>{stopAuto();if(index<game.moves.length){index++;update()}};$('prev').onclick=()=>{stopAuto();if(index>0){index--;update()}};$('restart').onclick=()=>{stopAuto();index=0;update()};$('autoPlay').onclick=toggleAuto;$('playSpeed').onchange=e=>{speed=Number(e.target.value)||1;if(playing)scheduleNext()};await hydrateGame(games[0])}
init().catch(e=>{$('headline').textContent='Không thể tải thư viện';$('narration').textContent=e.message||'Vui lòng kiểm tra kết nối.'});
